Finished javascript-loops-exercise. Lambert Nguyen
Ln1097/m1-1023-code-solutions pull request #11
Opened 2023-11-05 23:23 UTC by Ln1097

![Screenshot (175)](https://github.com/Ln1097/m1-1023-code-solutions/assets/106450990/4fb1b5f0-0244-4521-915f-3b0d6c3532b1)
![Screenshot (183)](https://github.com/Ln1097/m1-1023-code-solutions/assets/106450990/0605d247-3da3-4680-b009-123993a908e5)
![Screenshot (182)](https://github.com/Ln1097/m1-1023-code-solutions/assets/106450990/e5703399-92ab-4c42-80c3-d74e84167e2c)
![Screenshot (181)](https://github.com/Ln1097/m1-1023-code-solutions/assets/106450990/bdd5a3cb-af1a-428e-80e4-c71a1f079a06)

2023-11-06 23:44 UTC, kurtyazdizadeh requested changes
Take a look at my comments for some small changes!

2023-11-06 23:44 UTC, kurtyazdizadeh commented on javascript-loops.tar/javascript-loops/main.js
> +  for (let i = 0; i < 3; i++) {
`i < 3` is not right. That would only work for strings that are 3 characters long. What if I passed in a string longer than three characters? How could I re-write that expression to dynamically handle any length of string that is passed in from the argument?

2023-11-06 23:44 UTC, kurtyazdizadeh commented on javascript-loops.tar/javascript-loops/main.js
> +  for (let i = 0; i < 3; i++) {
same idea here, this only works if the `numbers` array had a length of 3. It shouldn't be hardcoded like this, what property on the `numbers` array could we use instead to dynamically handle the `length` in the for loop? 🤔

2023-11-07 03:58 UTC, Ln1097 commented
![Screenshot (188)](https://github.com/Ln1097/m1-1023-code-solutions/assets/106450990/56e9c98d-73b2-474a-b439-bd7e4c3616c3)

2023-11-07 04:03 UTC, kurtyazdizadeh approved these changes
Approved 👍

2023-11-08 03:59 UTC, merged