Finished html-tables exercise. Lambert Nguyen
Ln1097/m1-1023-code-solutions pull request #25
Opened 2023-11-20 22:53 UTC by Ln1097

![Screenshot (215)](https://github.com/Ln1097/m1-1023-code-solutions/assets/106450990/329a5ad6-e176-4e84-9dfb-01704cd04b66)

2023-11-21 02:20 UTC, kurtyazdizadeh requested changes
Very close! Just needs the missing `thead` and `tbody` elements to be semantically correct.

2023-11-21 02:20 UTC, kurtyazdizadeh commented on html-tables.tar/html-tables/index.html
> +  </tr>
there should be a `<thead>` element wrapping this `<tr>` element

2023-11-21 02:20 UTC, kurtyazdizadeh commented on html-tables.tar/html-tables/index.html
> +</tr>
there should be a`<tbody>` element wrapping this `<tr>` element.

2023-11-21 18:23 UTC, Ln1097 commented
fixed

2023-11-22 02:16 UTC, kurtyazdizadeh approved these changes
Approved 👍

2023-11-22 02:20 UTC, merged